### ISSUE TITLE
Consistency Level

### ISSUE THREAD

**Issue by panthershark** [tenmax/cqlkit#1]
Is there a way to set the consistency level on the connection for this tool? I need to be able to set QUORUM or ALL to get full export.  Without this, I get different row counts on each run.

**Comment by popcornylu** [comment]
It makes sense. I will consider to add this feature at next release.

**Comment by popcornylu** [comment]
Support consistency level at 0.2.0

**Comment by panthershark** [comment]
rad!  thank you.

**Comment by panthershark** [comment]
Also side note.  I'm posting this in case you get any issues submitted against cqlkit that are really C\* issues.

There was a really bad bug in some versions of C\* (https://issues.apache.org/jira/browse/CASSANDRA-8940) that caused me to think that cqlkit needed this consistency configuration.  

I'm definitely going to use the consistency flag in cqlkit, but the really ugly issue was this non-thread safe bug in C*.
https://issues.apache.org/jira/browse/CASSANDRA-8940

**Comment by popcornylu** [comment]
I think the easiest way to check if it is bug in cqlkit or c\* is to check the [Statement#getConsistencyLevel](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/Statement.html#getConsistencyLevel%28%29). or check if the same issue occurs in cqlsh. Still thanks for your information. ;)

**Comment by panthershark** [comment]
Yeah.  That combined with a lot of research led me to that bug report.  :)
