### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by Themesaul** [tenmax/cqlkit#12]
I downloaded the project. I have imported it in IntelliJ idea. When I compile with "build of gradle" and try to execute it, it says "the main class has not been found or loaded". What am I doing wrong? Is there another way to compile it? I do this because I need to implement another "Custom" data type

Thank you very much

**Comment by popcornylu** [comment]
The project uses gradle application plugins.

You can use gradle `installDist` task to install application to `build/install/cqlkit`

or 

`distZip` to manipulate the distribution zip file located at `build/distributions/`

All the task can be run directly by intellij gradle toolbar 

![image](https://user-images.githubusercontent.com/860633/38879132-2fcdd96c-4295-11e8-94e4-7bc8b5c34557.png)

**Comment by Themesaul** [comment]
Work like a charm!
