### ISSUE TITLE
Different value formats between cqlsh and cqlkit

### ISSUE THREAD

**Issue by cralcubo** [tenmax/cqlkit#20]
First of all thank you for creating this handy tool!

Having the following table:
user                   | order                  | created                         | deleted | score | progress 
-----------------------+------------------------+---------------------------------+---------+-------+-----------
mM0CJ0N2QBGOUife8Jv3Tg | 0GrxPSpj9tmcqEghLmtufg | 2020-04-02 09:03:16.933000+0000 |    null |    0  |     null 

Where:
- user and order are text columns
- created and deleted are timestamp columns
- score and progress are double columns

the exported CSV data for that row using cqlkit will look like this:
mM0CJ0N2QBGOUife8Jv3Tg,0GrxPSpj9tmcqEghLmtufg,2020-04-02 11:03:16.933+0200,,0.0,NULL

but using the COPY TO command in cqlsh the same row will look like this:
mM0CJ0N2QBGOUife8Jv3Tg,0GrxPSpj9tmcqEghLmtufg,2020-04-02 09:03:16.933+0000,,0,

As you can see there are differences in the outputs of cqlsh and cqlkit.

A double value looks like:
cqlsh : 0
cqlkit: 0.0

A null double:
cqlsh : '' <an empty string>
cqlkit: NULL

A timestamp:
cqlsh:  2020-04-02 09:03:16.933+0000
cqlkit:  2020-04-02 11:03:16.933+0200

It would be really handy to have an option in cqlkit that would allow to export the data in the same text format as cqlsh does, this becomes specially useful when you need to import the data exported by cqlkit using the COPY FROM command in cqlsh.

**Comment by phstudy** [comment]
Hi @cralcubo,
I think `timestamp timezone` and `null double` should be consistent with cqlsh.
But `zero double` seems not to be necessary, current format should be compatible with cqlsh.

**Comment by cralcubo** [comment]
Hi @phstudy 
You are right the zero double is definitively compatible with cqlsh.
Thanks for taking care of this issue.
Regards!

**Comment by phstudy** [comment]
Hi @cralcubo,
I have pre-released [v0.3.3](https://github.com/tenmax/cqlkit/releases/tag/v0.3.3).  Could you give it a try?

**Comment by cralcubo** [comment]
Hi @phstudy,

the null issue is fixed however timestamp is having now an inconsistency.
If you leave the default date-format the following timestamp will be exported:
2019-03-26T11:04:45.473+0000
If you specify the following date-format:"yyyy-MM-dd' 'HH:mm:ss.SSSZ" it will be exported:
2019-03-26 12:04:45.473+0100

**Comment by phstudy** [comment]
@cralcubo ,
I have adjusted the default datetime format. It currently should be consistent with cqlsh.
I also added another option `--time-zone` to support different time zone requirement.

The pre-released [v0.3.3 ](https://github.com/tenmax/cqlkit/releases/tag/v0.3.3) is updated. Could you try it again?

Thank you :D

**Comment by cralcubo** [comment]
Hi @phstudy , 

The issue with the time format is fixed, thanks! I found another inconsistency though:

A text column with data that includes double quotes like: ["USER_ACCESS","ACCESS_PUBLIC","PRACTICE_ORGANIZATION"]

will be exported using cqlkit as:
"[""USER_ACCESS"",""ACCESS_PUBLIC"",""PRACTICE_ORGANIZATION""]"
where cqlsh will export it as:
"[\"USER_ACCESS\",\"ACCESS_PUBLIC\",\"PRACTICE_ORGANIZATION\"]"

as you can see cqlsh will escape the double quote characters like java does but cqlkit will duplicate them, this format differences makes impossible to import the exported data back to cassandra.

**Comment by phstudy** [comment]
The output of CSV double quote follows [rfc-4180](https://tools.ietf.org/html/rfc4180). Maybe we can add another option for cqlsh.

**Comment by cralcubo** [comment]
Hi @phstudy ,

It is unfortunate that cqlsh: COPY FROM doesn't recognized the mentioned standard however adding an option to escape quotes in a text (like cqlsh does: \\") will definitively serve to my purpose, namely importing a csv file generated by cqlkit to a cassandra database.

Just for the record, I noticed that my previous comment was reformatted by the github editor, it should be:

> where cqlsh will export it as:
"[\\"USER_ACCESS\\",\\"ACCESS_PUBLIC\\",\\"PRACTICE_ORGANIZATION\\"]"

Kind regards

**Comment by phstudy** [comment]
Hi @cralcubo,

`COPY keyspace.tbl(text_col) TO 'filename' WITH ESCAPE='"';` should be able to output rfc-4180 format.

**Comment by cralcubo** [comment]
You are right @phstudy,

Thanks for your help.
