### ISSUE TITLE
cql2json does not wrap rows in container object

### ISSUE THREAD

**Issue by erhhung** [tenmax/cqlkit#8]
While cql2json outputs JSON for **individual rows**, it doesn't wrap all rows in a container object, making the command much less useful for piping the result to additional utilities that expect JSON input.

```
> cql2json -c localhost -k items -q "select id from items"
{"id":"anv79n"}
{"id":"hcp5yn"}

> cql2json -c localhost -k items -q "select id from items" | json_pp
garbage after JSON object, at character offset 17 (before ""id":"hcp5yn"}\n") at /usr/bin/json_pp5.18 line 45.
```

**Comment by phstudy** [comment]
This feature was implemented in v0.3.1.
